export const UI_ENTRY_POINTS = {
	CHANNEL_PAGE: 'channel_page',
	CHAT_VIEWER_CARD: 'chat_viewer_card',
	WHISPERS_THREAD: 'whispers_thread',
};
export const DEFAULT_UI_ENTRY_POINT = UI_ENTRY_POINTS.CHANNEL_PAGE;
export const SESSION_ID_LENGTH = 32;
export const WIZARD_VERSION = '1.0';
export const CONTENT_TYPES = {
	// not supported
	// ALERT_REPORT: 'ALERT_REPORT',
	// BITS_BADGE_REPORT: 'BITS_BADGE_REPORT',
	// CHANNEL_POINTS_REPORT: 'CHANNEL_POINTS_REPORT',
	// CLIP_REPORT: 'CLIP_REPORT',
	// COLLAB_REQUEST: 'COLLAB_REQUEST',
	// EMOTE_REPORT: 'EMOTE_REPORT',
	// EVENT_REPORT: 'EVENT_REPORT',
	// EXTENSION_REPORT: 'EXTENSION_REPORT',
	// GUEST_STAR_BACKSTAGE_REPORT: 'GUEST_STAR_BACKSTAGE_REPORT',
	// LIVE_UP_REPORT: 'LIVE_UP_REPORT',
	// MODERATOR_STRIKE_REASON: 'MODERATOR_STRIKE_REASON',
	// MOD_COMMENT: 'MOD_COMMENT',
	// POLL_REPORT: 'POLL_REPORT',
	// RAID_REPORT: 'RAID_REPORT',
	// REWARD_REDEMPTION_REPORT: 'REWARD_REDEMPTION_REPORT',
	// STORY_REPORT: 'STORY_REPORT',
	// SUB_BADGE_REPORT: 'SUB_BADGE_REPORT',
	// UNBAN_REQUEST_REPORT: 'UNBAN_REQUEST_REPORT',
	// VOD_COMMENT_REPORT: 'VOD_COMMENT_REPORT',
	// VOD_REPORT: 'VOD_REPORT',
	CHAT_REPORT: 'CHAT_REPORT',
	LIVESTREAM_REPORT: 'LIVESTREAM_REPORT',
	USERNAME_REPORT: 'USERNAME_REPORT',
	USER_REPORT: 'USER_REPORT',
	WHISPER_REPORT: 'WHISPER_REPORT',
};
